[project]
name = "effml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "pytest>=9.0.3",
    "pytest-xdist>=3.8.0",
    "torch>=2.10.0",
    "tqdm>=4.67.3",
    "triton-viz>=3.0",
    "unsloth",
]

[tool.pytest.ini_options]
pythonpath = ["."]
